import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'Introduction',
    'Request idempotency',
    'Pagination',
    'Cached usage responses',
    'Dry run requests',
    'Error response format',
    'Reliability and scaling',
    'Rate limits',
    'Webhooks',
    {
      type: 'category',
      label: 'Endpoints',
      items: [
        'Endpoints/scalartax',
        {
          type: 'category',
          label: 'Accounts',
          items: [
            'Endpoints/Accounts/create-account',   
            'Endpoints/Accounts/list-accounts', 
            'Endpoints/Accounts/fetch-account',
          ],
        },
        {
          type: 'category',
          label: 'Users',
          items: [
            'Endpoints/Users/create-user',   
            'Endpoints/Users/list-users', 
            'Endpoints/Users/fetch-user',
            'Endpoints/Users/update-user',
            'Endpoints/Users/delete-user'
          ],
        },
        {
          type: 'category',
          label: 'Customers',
          items: [
            'Endpoints/Customers/create-customer', 
            'Endpoints/Customers/list-customers', 
            'Endpoints/Customers/fetch-customer', 
            'Endpoints/Customers/update-customer', 
            'Endpoints/Customers/delete-customer'
          ],
        },
        {
          type: 'category',
          label: 'Entities',
          items: [
            'Endpoints/Entities/create-entity', 
            'Endpoints/Entities/list-entities', 
            'Endpoints/Entities/fetch-entity', 
            'Endpoints/Entities/update-entity', 
            'Endpoints/Entities/delete-entity'
          ],
        },
        {
          type: 'category',
          label: 'S_l_Nexuses',
          items: [
            'Endpoints/S_l_Nexuses/create-s-l-nexus', 
            'Endpoints/S_l_Nexuses/list-s-l-nexuses', 
            'Endpoints/S_l_Nexuses/fetch-s-l-nexus', 
            'Endpoints/S_l_Nexuses/update-s-l-nexus', 
            'Endpoints/S_l_Nexuses/delete-s-l-nexus'
          ],
        },
        {
          type: 'category',
          label: 'Products',
          items: [
            'Endpoints/Products/create-product', 
            'Endpoints/Products/list-products', 
            'Endpoints/Products/fetch-product', 
            'Endpoints/Products/update-product', 
            'Endpoints/Products/delete-product'
          ],
        },
        {
          type: 'category',
          label: 'Subscriptions',
          items: [
            'Endpoints/Subscriptions/create-subscription', 
            'Endpoints/Subscriptions/list-subscriptions', 
            'Endpoints/Subscriptions/fetch-subscription', 
            'Endpoints/Subscriptions/update-subscription', 
            'Endpoints/Subscriptions/delete-subscription'
          ],
        },
        {
          type: 'category',
          label: 'Locations',
          items: [
            'Endpoints/Locations/create-location', 
            'Endpoints/Locations/list-locations', 
            'Endpoints/Locations/fetch-location', 
            'Endpoints/Locations/update-location', 
            'Endpoints/Locations/delete-location'
          ],
        },
        {
          type: 'category',
          label: 'Exemption Certificates',
          items: [
            'Endpoints/Exemption Certificates/create-exemption-certificate', 
            'Endpoints/Exemption Certificates/list-exemption-certificates', 
            'Endpoints/Exemption Certificates/fetch-exemption-certificate', 
            'Endpoints/Exemption Certificates/update-exemption-certificate', 
            'Endpoints/Exemption Certificates/delete-exemption-certificate'
          ],
        },
        {
          type: 'category',
          label: 'Location Attributes',
          items: [
            'Endpoints/Location Attributes/create-location-attribute', 
            'Endpoints/Location Attributes/list-location-attributes', 
            'Endpoints/Location Attributes/fetch-location-attribute', 
            'Endpoints/Location Attributes/update-location-attribute', 
            'Endpoints/Location Attributes/delete-location-attribute'
          ],
        },
      ],
    },
    
  ],
   
};

export default sidebars;
